# Generated by Django 4.2.1 on 2024-02-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefunc', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
