# Generated by Django 4.2.1 on 2024-03-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefunc', '0009_tags_alter_post_cat_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='women', to='basefunc.tags'),
        ),
    ]
