# Generated by Django 4.2.1 on 2024-03-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefunc', '0010_rename_name_category_title_alter_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Husbands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('m_count', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
