# Generated by Django 4.2.1 on 2024-03-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefunc', '0011_husbands'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['title'], 'verbose_name': 'Woman', 'verbose_name_plural': 'Women'},
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.IntegerField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
