# Generated by Django 4.2.1 on 2024-03-20 19:12

import autoslug.fields
import basefunc.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basefunc', '0014_category_autoslug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='autoslug',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=basefunc.models.custom_slugify),
        ),
    ]
