# Generated by Django 4.2.1 on 2024-03-20 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basefunc', '0017_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
