# Generated by Django 4.2.1 on 2024-03-20 19:40

import autoslug.fields
import basefunc.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basefunc', '0018_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='title', slugify=basefunc.models.custom_slugify),
        ),
    ]
