# Generated by Django 4.2.1 on 2024-03-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefunc', '0020_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.IntegerField(choices=[(1, 'Черновик'), (0, 'Опубликовано')], default=1),
        ),
    ]
