# Generated by Django 4.2.1 on 2024-04-11 11:06

import autoslug.fields
import basefunc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefunc', '0021_alter_post_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.IntegerField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=basefunc.models.custom_slugify, unique=True),
        ),
    ]
